version: "3.9"

services:
  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: verySecretPassword
      POSTGRES_USER: administrator
      POSTGRES_DB: todo

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    volumes: 
      - ./todo:/app/todo 
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://administrator:verySecretPassword@database:5432/todo
      CELERY_BROKER_URL: redis://redis:6379 
      CELERY_RESULT_BACKEND: redis://redis:6379 
    ports:
      - "6400:6400"
    depends_on:
      - database

  redis: 
    image: redis:latest 
    restart: unless-stopped
    ports: 
      - "6379:6379"

  worker: 
    build: 
      context: . 
      dockerfile: Dockerfile.dev 
    restart: unless-stopped
    environment: 
      CELERY_BROKER_URL: redis://redis:6379 
      CELERY_RESULT_BACKEND: redis://redis:6379 
    command: poetry run celery --app todo.tasks.ical worker --loglevel=info #This will overwrite the run command for the dockerfile.dev and only keep the same dependencies etc.
    
